# Task 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
scores = pd.read_csv("data_safe_copy.csv")

In [83]:
scores.shape[0]

300

In [8]:
scores.head()

  student_id cohort   module assignment  score
0       S001  alpha  Module1         A1     78
1       S001  alpha  Module1         A2     84
2       S001  alpha  Module2         A1     79
3       S001  alpha  Module2         A2     86
4       S001  alpha  Module3         A1     81

In [9]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  300 non-null    object
 1   cohort      300 non-null    object
 2   module      300 non-null    object
 3   assignment  300 non-null    object
 4   score       300 non-null    int64
dtypes: int64(1), object(4)
memory usage: 11.8+ KB

In [14]:
is_numeric = pd.api.types.is_numeric_dtype(scores['score'])
print(f"\nIs the 'score' column numeric? {is_numeric}")

Is the 'score' column numeric? True

# Task 2

In [41]:
data = {
    'student_id': [f"S06{i}" for i in range(10)],
    'status': ['active', 'inactive', 'active', 'inactive', 'active', 
               'inactive', 'active', 'inactive', 'active', 'inactive']
}

roster = pd.DataFrame(data)

In [42]:
roster

  student_id    status
0       S060    active
1       S061  inactive
2       S062    active
3       S063  inactive
4       S064    active
5       S065  inactive
6       S066    active
7       S067  inactive
8       S068    active
9       S069  inactive

In [47]:
merged_df = pd.merge(scores,roster, how = "left", on = "student_id")

In [49]:
merged_df.head()

  student_id cohort   module assignment  score status
0       S001  alpha  Module1         A1     78    NaN
1       S001  alpha  Module1         A2     84    NaN
2       S001  alpha  Module2         A1     79    NaN
3       S001  alpha  Module2         A2     86    NaN
4       S001  alpha  Module3         A1     81    NaN

In [51]:
missing_status_count = merged_df['status'].isna().sum()

print(f"NAN values in status column: {missing_status_count}")

NAN values in status column: 300

# Task 3

In [58]:
avg_by_module=merged_df.groupby(["cohort","module"])['score'].mean().reset_index()

In [59]:
avg_by_module

  cohort   module      score
0  alpha  Module1  77.970588
1  alpha  Module2  78.382353
2  alpha  Module3  79.794118
3   beta  Module1  78.647059
4   beta  Module2  78.411765
5   beta  Module3  80.029412
6  gamma  Module1  76.218750
7  gamma  Module2  76.468750
8  gamma  Module3  77.843750

In [60]:
avg_by_cohort = scores.groupby('cohort')['score'].mean().reset_index()
avg_by_cohort

  cohort      score
0  alpha  78.715686
1   beta  79.029412
2  gamma  76.843750

In [63]:
rolled_up = avg_by_module.groupby('cohort')['score'].mean()

print("avg with module:")
print(rolled_up)

print("\navg with cohort(original):")
print(avg_by_cohort.set_index('cohort')['score'])

avg with module:
cohort
alpha    78.715686
beta     79.029412
gamma    76.843750
Name: score, dtype: float64

avg with cohort(original):
cohort
alpha    78.715686
beta     79.029412
gamma    76.843750
Name: score, dtype: float64

# Task 4

In [68]:
student_module_report = scores.pivot_table(index="student_id", columns="module", values="score",aggfunc="mean")
student_module_report.head()

module      Module1  Module2  Module3
student_id
S001           81.0     82.5     84.5
S002           73.5     72.0     75.0
S003           87.5     88.5     89.5
S004           68.5     67.5     69.5
S005           81.5     82.5     83.5

In [70]:
student_module_report.index

Index(['S001', 'S002', 'S003', 'S004', 'S005', 'S006', 'S007', 'S008', 'S009',
       'S010', 'S011', 'S012', 'S013', 'S014', 'S015', 'S016', 'S017', 'S018',
       'S019', 'S020', 'S021', 'S022', 'S023', 'S024', 'S025', 'S026', 'S027',
       'S028', 'S029', 'S030', 'S031', 'S032', 'S033', 'S034', 'S035', 'S036',
       'S037', 'S038', 'S039', 'S040', 'S041', 'S042', 'S043', 'S044', 'S045',
       'S046', 'S047', 'S048', 'S049', 'S050'],
      dtype='object', name='student_id')

In [79]:
scores["student_id"].unique() == student_module_report.index

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [82]:
unique_students_count = scores['student_id'].nunique()
report_rows_count = student_module_report.shape[0]

unique_modules = sorted(scores['module'].unique())
report_columns = sorted(student_module_report.columns.tolist())

print(f"Original unique student count: {unique_students_count}")
print(f"Report row count: {report_rows_count}")

row_check = "Successful" if unique_students_count == report_rows_count else "Error!"
print(f"Validation 1 (Rows): {row_check}")

print("-" * 30)

print(f"Original modules: {unique_modules}")
print(f"Report columns: {report_columns}")
col_check = "Successful" if unique_modules == report_columns else "Error!"
print(f"Validation 2 (Columns): {col_check}")

Original unique student count: 50
Report row count: 50
Validation 1 (Rows): Successful
------------------------------
Original modules: ['Module1', 'Module2', 'Module3']
Report columns: ['Module1', 'Module2', 'Module3']
Validation 2 (Columns): Successful

# Task 5

In [84]:
student_avgs = scores.groupby(['student_id', 'cohort'])['score'].mean().reset_index()
top_students = student_avgs.sort_values(['cohort', 'score'], ascending=[True, False]) \
                           .groupby('cohort') \
                           .head(3) \
                           .reset_index(drop=True)

top_students.columns = ['student_id', 'cohort', 'avg_score']


print("Top 3 Students by Cohort:")
print(top_students)

Top 3 Students by Cohort:
  student_id cohort  avg_score
0       S003  alpha       88.5
1       S049  alpha       88.5
2       S027  alpha       86.5
3       S045   beta       90.5
4       S007   beta       89.5
5       S021   beta       88.5
6       S014  gamma       92.5
7       S040  gamma       84.5
8       S016  gamma       84.0